[project]
name = "meal_assistant"
version = "0.1.0"
description = "A smart recipe generation assistant."
authors = [{ name = "Your Name", email = "your@email.com" }]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"